<?php

namespace Database\Seeders;

use App\Models\Homestay;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class HomestaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $homestays = [
            ['user_id' => 2, 'kodebumdes' => 'BDSA001', 'name' => 'Homestay Mawar', 'description' => 'Penginapan nyaman di pusat desa.', 'address' => 'Desa A, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan A', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA002', 'name' => 'Homestay Melati', 'description' => 'Penginapan asri dengan pemandangan sawah.', 'address' => 'Desa B, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan B', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA003', 'name' => 'Homestay Anggrek', 'description' => 'Penginapan modern dengan fasilitas lengkap.', 'address' => 'Desa C, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan C', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA004', 'name' => 'Homestay Dahlia', 'description' => 'Penginapan nyaman di dekat pasar desa.', 'address' => 'Desa D, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan D', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA005', 'name' => 'Homestay Kenanga', 'description' => 'Penginapan dengan suasana pedesaan.', 'address' => 'Desa E, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan E', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA006', 'name' => 'Homestay Cempaka', 'description' => 'Penginapan dekat dengan objek wisata.', 'address' => 'Desa F, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan F', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA007', 'name' => 'Homestay Teratai', 'description' => 'Penginapan dengan fasilitas kolam renang.', 'address' => 'Desa G, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan G', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA008', 'name' => 'Homestay Kamboja', 'description' => 'Penginapan dengan suasana tenang.', 'address' => 'Desa H, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan H', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA009', 'name' => 'Homestay Bougenville', 'description' => 'Penginapan dengan taman bunga.', 'address' => 'Desa I, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan I', 'status' => 'terverifikasi'],
            ['user_id' => 2, 'kodebumdes' => 'BDSA010', 'name' => 'Homestay Flamboyan', 'description' => 'Penginapan dengan fasilitas olahraga.', 'address' => 'Desa J, Kutowinangun', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kutowinangun', 'kelurahan' => 'Kelurahan J', 'status' => 'terverifikasi'],
            ['user_id' => 3, 'kodebumdes' => 'BDSB001', 'name' => 'Homestay Sakura', 'description' => 'Penginapan nyaman di tepi pantai.', 'address' => 'Desa K, Ambal', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Ambal', 'kelurahan' => 'Kelurahan K', 'status' => 'terverifikasi'],
            ['user_id' => 3, 'kodebumdes' => 'BDSB002', 'name' => 'Homestay Edelweis', 'description' => 'Penginapan strategis dekat stasiun.', 'address' => 'Desa L, Karanganyar', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Karanganyar', 'kelurahan' => 'Kelurahan L', 'status' => 'terverifikasi'],
            ['user_id' => 4, 'kodebumdes' => 'BDSC001', 'name' => 'Homestay Lavender', 'description' => 'Penginapan di kawasan pegunungan.', 'address' => 'Desa M, Sruweng', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Sruweng', 'kelurahan' => 'Kelurahan M', 'status' => 'terverifikasi'],
            ['user_id' => 4, 'kodebumdes' => 'BDSC002', 'name' => 'Homestay Tulip', 'description' => 'Penginapan dekat area wisata air terjun.', 'address' => 'Desa N, Ayah', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Ayah', 'kelurahan' => 'Kelurahan N', 'status' => 'terverifikasi'],
            ['user_id' => 5, 'kodebumdes' => 'BDSD001', 'name' => 'Homestay Magnolia', 'description' => 'Penginapan di pusat kota.', 'address' => 'Desa O, Kebumen', 'provinsi' => 'Jawa Tengah', 'kabupaten' => 'Kebumen', 'kecamatan' => 'Kebumen', 'kelurahan' => 'Kelurahan O', 'status' => 'terverifikasi'],
            
            // 10 homestay di Wonosobo, Jawa Barat
            ['user_id' => 6, 'kodebumdes' => 'BDSD002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa P1, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P1', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa P2, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P2', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD004', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa P3, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P3', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD005', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa P4, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P4', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD006', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa P5, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P5', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD007', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa P6, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P6', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD008', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa P7, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P7', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD009', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa P8, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P8', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD010', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa P9, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P9', 'status' => 'terverifikasi'],
            ['user_id' => 6, 'kodebumdes' => 'BDSD011', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa P10, Wonosobo', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Wonosobo', 'kecamatan' => 'Wonosobo', 'kelurahan' => 'Kelurahan P10', 'status' => 'terverifikasi'],

            // 10 homestay di Bandung, Jawa Barat
            ['user_id' => 7, 'kodebumdes' => 'BDSE001', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa Q1, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q1', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa Q2, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q2', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE003', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa Q3, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q3', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE004', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa Q4, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q4', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE005', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa Q5, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q5', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE006', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa Q6, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q6', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE007', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa Q7, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q7', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE008', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa Q8, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q8', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE009', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa Q9, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q9', 'status' => 'terverifikasi'],
            ['user_id' => 7, 'kodebumdes' => 'BDSE010', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa Q10, Bandung', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bandung', 'kecamatan' => 'Lembang', 'kelurahan' => 'Kelurahan Q10', 'status' => 'terverifikasi'],

            // 10 homestay di Samosir, Sumatera Utara
            ['user_id' => 8, 'kodebumdes' => 'BDSF001', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa R1, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R1', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa R2, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R2', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa R3, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R3', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF004', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa R4, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R4', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF005', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa R5, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R5', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF006', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa R6, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R6', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF007', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa R7, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R7', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF008', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa R8, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R8', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF009', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa R9, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R9', 'status' => 'terverifikasi'],
            ['user_id' => 8, 'kodebumdes' => 'BDSF010', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa R10, Samosir', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Samosir', 'kecamatan' => 'Pangururan', 'kelurahan' => 'Kelurahan R10', 'status' => 'terverifikasi'],

            // 10 homestay di Sleman, DI Yogyakarta
            ['user_id' => 9, 'kodebumdes' => 'BDSG001', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa S1, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S1', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa S2, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S2', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa S3, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S3', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG004', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa S4, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S4', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG005', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa S5, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S5', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG006', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa S6, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S6', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG007', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa S7, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S7', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG008', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa S8, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S8', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG009', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa S9, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S9', 'status' => 'terverifikasi'],
            ['user_id' => 9, 'kodebumdes' => 'BDSG010', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa S10, Sleman', 'provinsi' => 'DI Yogyakarta', 'kabupaten' => 'Sleman', 'kecamatan' => 'Pakem', 'kelurahan' => 'Kelurahan S10', 'status' => 'terverifikasi'],

            // 10 homestay di Palembang, Sumatera Selatan
            ['user_id' => 10, 'kodebumdes' => 'BDSH001', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa T1, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T1', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa T2, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T2', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa T3, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T3', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH004', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa T4, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T4', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH005', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa T5, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T5', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH006', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa T6, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T6', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH007', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa T7, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T7', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH008', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa T8, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T8', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH009', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa T9, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T9', 'status' => 'terverifikasi'],
            ['user_id' => 10, 'kodebumdes' => 'BDSH010', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa T10, Palembang', 'provinsi' => 'Sumatera Selatan', 'kabupaten' => 'Palembang', 'kecamatan' => 'Ilir Barat', 'kelurahan' => 'Kelurahan T10', 'status' => 'terverifikasi'],

            // 10 homestay di Jember, Jawa Timur
            ['user_id' => 11, 'kodebumdes' => 'BDSI001', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa U1, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U1', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa U2, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U2', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa U3, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U3', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI004', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa U4, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U4', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI005', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa U5, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U5', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI006', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa U6, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U6', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI007', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa U7, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U7', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI008', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa U8, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U8', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI009', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa U9, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U9', 'status' => 'terverifikasi'],
            ['user_id' => 11, 'kodebumdes' => 'BDSI010', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa U10, Jember', 'provinsi' => 'Jawa Timur', 'kabupaten' => 'Jember', 'kecamatan' => 'Sumbersari', 'kelurahan' => 'Kelurahan U10', 'status' => 'terverifikasi'],

            // 10 homestay di Pontianak, Kalimantan Barat
            ['user_id' => 12, 'kodebumdes' => 'BDSJ001', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa V1, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V1', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa V2, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V2', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa V3, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V3', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ004', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa V4, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V4', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ005', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa V5, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V5', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ006', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa V6, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V6', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ007', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa V7, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V7', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ008', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa V8, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V8', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ009', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa V9, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V9', 'status' => 'terverifikasi'],
            ['user_id' => 12, 'kodebumdes' => 'BDSJ010', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa V10, Pontianak', 'provinsi' => 'Kalimantan Barat', 'kabupaten' => 'Pontianak', 'kecamatan' => 'Pontianak Selatan', 'kelurahan' => 'Kelurahan V10', 'status' => 'terverifikasi'],

            // 10 homestay di Medan, Sumatera Utara
            ['user_id' => 13, 'kodebumdes' => 'BDSK001', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa W1, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W1', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa W2, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W2', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa W3, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W3', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK004', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa W4, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W4', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK005', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa W5, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W5', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK006', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa W6, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W6', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK007', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa W7, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W7', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK008', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa W8, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W8', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK009', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa W9, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W9', 'status' => 'terverifikasi'],
            ['user_id' => 13, 'kodebumdes' => 'BDSK010', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa W10, Medan', 'provinsi' => 'Sumatera Utara', 'kabupaten' => 'Medan', 'kecamatan' => 'Medan Baru', 'kelurahan' => 'Kelurahan W10', 'status' => 'terverifikasi'],

            // 10 homestay di Bogor, Jawa Barat
            ['user_id' => 14, 'kodebumdes' => 'BDSL001', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa X1, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X1', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa X2, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X2', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa X3, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X3', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL004', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa X4, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X4', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL005', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa X5, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X5', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL006', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa X6, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X6', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL007', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa X7, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X7', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL008', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa X8, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X8', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL009', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa X9, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X9', 'status' => 'terverifikasi'],
            ['user_id' => 14, 'kodebumdes' => 'BDSL010', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa X10, Bogor', 'provinsi' => 'Jawa Barat', 'kabupaten' => 'Bogor', 'kecamatan' => 'Ciawi', 'kelurahan' => 'Kelurahan X10', 'status' => 'terverifikasi'],

            // 10 homestay di Denpasar, Bali
            ['user_id' => 15, 'kodebumdes' => 'BDSM001', 'name' => 'Homestay Alpukat', 'description' => 'Penginapan di kawasan pertanian.', 'address' => 'Desa Y1, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y1', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM002', 'name' => 'Homestay Pinus', 'description' => 'Penginapan di tengah hutan pinus.', 'address' => 'Desa Y2, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y2', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM003', 'name' => 'Homestay Cemara', 'description' => 'Penginapan sejuk di dataran tinggi.', 'address' => 'Desa Y3, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y3', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM004', 'name' => 'Homestay Meranti', 'description' => 'Penginapan dekat danau.', 'address' => 'Desa Y4, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y4', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM005', 'name' => 'Homestay Jati', 'description' => 'Penginapan di kawasan wisata alam.', 'address' => 'Desa Y5, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y5', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM006', 'name' => 'Homestay Mahoni', 'description' => 'Penginapan di tepi sungai.', 'address' => 'Desa Y6, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y6', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM007', 'name' => 'Homestay Akasia', 'description' => 'Penginapan di kawasan perkebunan.', 'address' => 'Desa Y7, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y7', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM008', 'name' => 'Homestay Duren', 'description' => 'Penginapan dekat kebun durian.', 'address' => 'Desa Y8, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y8', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM009', 'name' => 'Homestay Rambutan', 'description' => 'Penginapan di kawasan buah-buahan.', 'address' => 'Desa Y9, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y9', 'status' => 'terverifikasi'],
            ['user_id' => 15, 'kodebumdes' => 'BDSM010', 'name' => 'Homestay Salak', 'description' => 'Penginapan di kaki gunung.', 'address' => 'Desa Y10, Denpasar', 'provinsi' => 'Bali', 'kabupaten' => 'Denpasar', 'kecamatan' => 'Denpasar Selatan', 'kelurahan' => 'Kelurahan Y10', 'status' => 'terverifikasi'],
        ];

        foreach ($homestays as $homestay) {
            Homestay::create($homestay);
        }
    }
}

