<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Admin User',
                'email' => 'admin@nazma.com',
                'password' => bcrypt('12345678'),
                'nomorhp' => '081234567890',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Kebumen',
                'kecamatan' => 'Kecamatan 1',
                'kelurahan' => 'Kelurahan 1',
                'address' => 'Alamat 1',
                'gender' => 'L',
                'foto' => null,
                'role' => 'admin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Owner User',
                'email' => 'owner@nazma.com',
                'password' => bcrypt('12345678'),
                'nomorhp' => '081234567891',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Kebumen',
                'kecamatan' => 'Kecamatan 2',
                'kelurahan' => 'Kelurahan 2',
                'address' => 'Alamat 2',
                'gender' => 'P',
                'foto' => null,
                'role' => 'owner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Subadmin User',
                'email' => 'subadmin@nazma.com',
                'password' => bcrypt('12345678'),
                'nomorhp' => '081234567892',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Kebumen',
                'kecamatan' => 'Kecamatan 3',
                'kelurahan' => 'Kelurahan 3',
                'address' => 'Alamat 3',
                'gender' => 'L',
                'foto' => null,
                'role' => 'subadmin',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guest User',
                'email' => 'guest@nazma.com',
                'password' => bcrypt('12345678'),
                'nomorhp' => '081234567893',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Kebumen',
                'kecamatan' => 'Kecamatan 4',
                'kelurahan' => 'Kelurahan 4',
                'address' => 'Alamat 4',
                'gender' => 'P',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 1',
                'email' => 'random1@nazma.com',
                'password' => bcrypt('password1'),
                'nomorhp' => '081234567894',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bandung',
                'kecamatan' => 'Kecamatan 5',
                'kelurahan' => 'Kelurahan 5',
                'address' => 'Alamat 5',
                'gender' => 'L',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 2',
                'email' => 'random2@nazma.com',
                'password' => bcrypt('password2'),
                'nomorhp' => '081234567895',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Surabaya',
                'kecamatan' => 'Kecamatan 6',
                'kelurahan' => 'Kelurahan 6',
                'address' => 'Alamat 6',
                'gender' => 'P',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 3',
                'email' => 'random3@nazma.com',
                'password' => bcrypt('password3'),
                'nomorhp' => '081234567896',
                'provinsi' => 'DKI Jakarta',
                'kabupaten' => 'Jakarta Selatan',
                'kecamatan' => 'Kecamatan 7',
                'kelurahan' => 'Kelurahan 7',
                'address' => 'Alamat 7',
                'gender' => 'L',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 4',
                'email' => 'random4@nazma.com',
                'password' => bcrypt('password4'),
                'nomorhp' => '081234567897',
                'provinsi' => 'Banten',
                'kabupaten' => 'Tangerang',
                'kecamatan' => 'Kecamatan 8',
                'kelurahan' => 'Kelurahan 8',
                'address' => 'Alamat 8',
                'gender' => 'P',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 5',
                'email' => 'random5@nazma.com',
                'password' => bcrypt('password5'),
                'nomorhp' => '081234567898',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'kecamatan' => 'Kecamatan 9',
                'kelurahan' => 'Kelurahan 9',
                'address' => 'Alamat 9',
                'gender' => 'L',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 6',
                'email' => 'random6@nazma.com',
                'password' => bcrypt('password6'),
                'nomorhp' => '081234567899',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Malang',
                'kecamatan' => 'Kecamatan 10',
                'kelurahan' => 'Kelurahan 10',
                'address' => 'Alamat 10',
                'gender' => 'P',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 7',
                'email' => 'random7@nazma.com',
                'password' => bcrypt('password7'),
                'nomorhp' => '081234567900',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bekasi',
                'kecamatan' => 'Kecamatan 11',
                'kelurahan' => 'Kelurahan 11',
                'address' => 'Alamat 11',
                'gender' => 'L',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 8',
                'email' => 'random8@nazma.com',
                'password' => bcrypt('password8'),
                'nomorhp' => '081234567901',
                'provinsi' => 'Bali',
                'kabupaten' => 'Denpasar',
                'kecamatan' => 'Kecamatan 12',
                'kelurahan' => 'Kelurahan 12',
                'address' => 'Alamat 12',
                'gender' => 'P',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 9',
                'email' => 'random9@nazma.com',
                'password' => bcrypt('password9'),
                'nomorhp' => '081234567902',
                'provinsi' => 'Sumatera Utara',
                'kabupaten' => 'Medan',
                'kecamatan' => 'Kecamatan 13',
                'kelurahan' => 'Kelurahan 13',
                'address' => 'Alamat 13',
                'gender' => 'L',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 10',
                'email' => 'random10@nazma.com',
                'password' => bcrypt('password10'),
                'nomorhp' => '081234567903',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Solo',
                'kecamatan' => 'Kecamatan 14',
                'kelurahan' => 'Kelurahan 14',
                'address' => 'Alamat 14',
                'gender' => 'P',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 11',
                'email' => 'random11@nazma.com',
                'password' => bcrypt('password11'),
                'nomorhp' => '081234567904',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Depok',
                'kecamatan' => 'Kecamatan 15',
                'kelurahan' => 'Kelurahan 15',
                'address' => 'Alamat 15',
                'gender' => 'L',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 12',
                'email' => 'random12@nazma.com',
                'password' => bcrypt('password12'),
                'nomorhp' => '081234567905',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Sidoarjo',
                'kecamatan' => 'Kecamatan 16',
                'kelurahan' => 'Kelurahan 16',
                'address' => 'Alamat 16',
                'gender' => 'P',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Random User 13',
                'email' => 'random13@nazma.com',
                'password' => bcrypt('password13'),
                'nomorhp' => '081234567906',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Magelang',
                'kecamatan' => 'Kecamatan 17',
                'kelurahan' => 'Kelurahan 17',
                'address' => 'Alamat 17',
                'gender' => 'L',
                'foto' => null,
                'role' => 'guest',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        User::insert($users);
    }
}

